<template>
  <div class="page-wrapper">
    <LandingNavbar />
    <main>

      <section class="page-hero">
        <div class="container">
          <div class="hero-badge">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" width="16" height="16">
              <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75m-3-7.036A11.959 11.959 0 0 1 3.598 6 11.99 11.99 0 0 0 3 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285Z" />
            </svg>
            Last Updated: March 1, 2026
          </div>
          <h1 class="page-title">Privacy Policy</h1>
          <p class="page-subtitle">We take your privacy seriously. This policy explains what data we collect, how we use it, and your rights as a user of Archangel Payroll.</p>
        </div>
      </section>

      <section class="legal-section">
        <div class="container">
          <div class="legal-layout">

            <!-- TOC -->
            <nav class="toc-nav">
              <div class="toc-title">Contents</div>
              <ul>
                <li v-for="section in sections" :key="section.id">
                  <a :href="`#${section.id}`" class="toc-link">{{ section.title }}</a>
                </li>
              </ul>
            </nav>

            <!-- Content -->
            <article class="legal-content">

              <div class="intro-callout">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" width="20" height="20">
                  <path stroke-linecap="round" stroke-linejoin="round" d="m11.25 11.25.041-.02a.75.75 0 0 1 1.063.852l-.708 2.836a.75.75 0 0 0 1.063.853l.041-.021M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9-3.75h.008v.008H12V8.25Z" />
                </svg>
                <p>This Privacy Policy applies to Archangel Technologies Inc. ("Archangel Payroll," "we," "us," or "our") and governs data collection and usage for our payroll platform and related services.</p>
              </div>

              <section id="information-we-collect">
                <h2>1. Information We Collect</h2>
                <p>We collect information you provide directly to us, information generated by your use of the service, and information from third parties.</p>
                <h3>Account Information</h3>
                <p>When you create an account, we collect your name, email address, company name, phone number, and billing information.</p>
                <h3>Employee Data</h3>
                <p>As a payroll processor, we collect and process employee data on your behalf, including: full legal names, Social Security Numbers (SSNs) or Tax IDs, addresses, dates of birth, bank account information for direct deposit, compensation and benefits data, and employment status information.</p>
                <h3>Usage Data</h3>
                <p>We automatically collect information about how you access and use the platform, including IP addresses, browser type, pages visited, time spent, and actions taken.</p>
              </section>

              <section id="how-we-use-information">
                <h2>2. How We Use Your Information</h2>
                <p>We use the information we collect to:</p>
                <ul>
                  <li>Provide, operate, and improve the Archangel Payroll platform</li>
                  <li>Process payroll, tax filings, and related transactions on your behalf</li>
                  <li>Communicate with you about your account, updates, and support issues</li>
                  <li>Comply with legal obligations including tax reporting requirements</li>
                  <li>Detect and prevent fraud, security incidents, and abuse</li>
                  <li>Analyze usage trends to improve the platform</li>
                </ul>
                <p>We do not sell your personal information or your employees' data to third parties.</p>
              </section>

              <section id="data-sharing">
                <h2>3. Data Sharing and Disclosure</h2>
                <p>We may share information in the following circumstances:</p>
                <h3>Service Providers</h3>
                <p>We work with third-party vendors who assist us in providing the service (e.g., cloud hosting, payment processors, tax filing agencies). These providers are contractually obligated to protect your data.</p>
                <h3>Legal Requirements</h3>
                <p>We may disclose information to government authorities (such as tax agencies) as required by law, or to comply with legal process.</p>
                <h3>Business Transfers</h3>
                <p>In the event of a merger, acquisition, or sale of assets, your data may be transferred. We will notify you before your data is transferred and becomes subject to a different privacy policy.</p>
              </section>

              <section id="data-security">
                <h2>4. Data Security</h2>
                <p>We implement industry-standard security measures to protect your data, including:</p>
                <ul>
                  <li>AES-256 encryption for data at rest</li>
                  <li>TLS 1.3 for all data in transit</li>
                  <li>SOC 2 Type II certified infrastructure</li>
                  <li>Role-based access controls and multi-factor authentication</li>
                  <li>Regular penetration testing and security audits</li>
                </ul>
                <p>No method of transmission over the Internet or electronic storage is 100% secure. We strive to use commercially acceptable means to protect your data but cannot guarantee absolute security.</p>
              </section>

              <section id="data-retention">
                <h2>5. Data Retention</h2>
                <p>We retain your data for as long as your account is active or as needed to provide services. We will retain and use your information as necessary to comply with legal obligations (payroll records are generally required to be retained for 3–7 years), resolve disputes, and enforce our agreements.</p>
                <p>Upon account termination, we will delete or anonymize your personal data within 90 days, except where retention is required by law.</p>
              </section>

              <section id="your-rights">
                <h2>6. Your Rights</h2>
                <p>Depending on your location, you may have the following rights regarding your personal data:</p>
                <ul>
                  <li><strong>Access:</strong> Request a copy of the personal data we hold about you.</li>
                  <li><strong>Correction:</strong> Request that we correct inaccurate or incomplete data.</li>
                  <li><strong>Deletion:</strong> Request deletion of your personal data, subject to legal retention requirements.</li>
                  <li><strong>Portability:</strong> Receive your data in a structured, machine-readable format.</li>
                  <li><strong>Objection:</strong> Object to certain types of processing of your data.</li>
                </ul>
                <p>To exercise your rights, contact us at <a href="mailto:privacy@archangelpayroll.com">privacy@archangelpayroll.com</a>.</p>
              </section>

              <section id="cookies">
                <h2>7. Cookies and Tracking</h2>
                <p>We use cookies and similar tracking technologies to operate and improve our service. We use session cookies (which expire when you close your browser) and persistent cookies (which remain until deleted).</p>
                <p>You can control cookies through your browser settings. Disabling cookies may affect your ability to use certain features of the platform.</p>
              </section>

              <section id="children">
                <h2>8. Children's Privacy</h2>
                <p>Archangel Payroll is not intended for use by individuals under 16 years of age. We do not knowingly collect personal information from children. If you believe we have inadvertently collected such information, please contact us immediately.</p>
              </section>

              <section id="changes">
                <h2>9. Changes to This Policy</h2>
                <p>We may update this Privacy Policy from time to time. We will notify you of material changes by posting the new policy on this page and updating the "Last Updated" date. We encourage you to review this policy periodically.</p>
              </section>

              <section id="contact">
                <h2>10. Contact Us</h2>
                <p>If you have questions about this Privacy Policy or our data practices, please contact:</p>
                <div class="contact-block">
                  <div><strong>Archangel Technologies Inc.</strong></div>
                  <div>Attn: Privacy Team</div>
                  <div>Email: <a href="mailto:privacy@archangelpayroll.com">privacy@archangelpayroll.com</a></div>
                </div>
              </section>

            </article>
          </div>
        </div>
      </section>

    </main>
    <LandingFooter />
  </div>
</template>

<script setup>
import LandingNavbar from '@/components/landing/LandingNavbar.vue'
import LandingFooter from '@/components/landing/LandingFooter.vue'

const sections = [
  { id: 'information-we-collect', title: '1. Information We Collect' },
  { id: 'how-we-use-information', title: '2. How We Use Your Information' },
  { id: 'data-sharing', title: '3. Data Sharing and Disclosure' },
  { id: 'data-security', title: '4. Data Security' },
  { id: 'data-retention', title: '5. Data Retention' },
  { id: 'your-rights', title: '6. Your Rights' },
  { id: 'cookies', title: '7. Cookies and Tracking' },
  { id: 'children', title: '8. Children\'s Privacy' },
  { id: 'changes', title: '9. Changes to This Policy' },
  { id: 'contact', title: '10. Contact Us' },
]
</script>

<style scoped>
.container { width: 100%; max-width: 1280px; margin: 0 auto; padding: 0 clamp(1rem, 4vw, 2rem); }

.page-hero {
  padding-top: calc(clamp(3rem, 8vw, 5rem) + 72px);
  padding-bottom: clamp(2rem, 5vw, 4rem);
  background-color: #001a5e;
  background-image: linear-gradient(155deg, #001a5e 0%, #0047AB 45%, #003a8c 100%);
  color: white; text-align: center;
}
.hero-badge {
  display: inline-flex; align-items: center; gap: 0.45rem;
  background: rgba(245, 166, 35, 0.18); border: 1px solid rgba(245, 166, 35, 0.4);
  color: #F5A623; padding: 0.45rem 1rem; border-radius: 9999px;
  font-size: 0.85rem; font-weight: 600; margin-bottom: 1.5rem;
}
.page-title { font-size: clamp(2rem, 6vw, 3rem); font-weight: 800; margin-bottom: 1.25rem; line-height: 1.15; letter-spacing: -0.02em; }
.page-subtitle { font-size: clamp(1rem, 2.5vw, 1.15rem); opacity: 0.88; line-height: 1.7; font-weight: 300; max-width: 600px; margin: 0 auto; }

.legal-section { padding: clamp(3rem, 7vw, 5rem) 0; background: #f0f4f8; }
.legal-layout { display: grid; grid-template-columns: 1fr; gap: 2.5rem; }
@media (min-width: 1024px) { .legal-layout { grid-template-columns: 260px 1fr; } }

/* TOC */
.toc-nav { background: white; border-radius: 14px; padding: 1.5rem; border: 1px solid #dde3ee; height: fit-content; position: sticky; top: 100px; }
.toc-title { font-size: 0.75rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #6b7280; margin-bottom: 1rem; }
.toc-nav ul { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 0.25rem; }
.toc-link { font-size: 0.88rem; color: #4b5563; text-decoration: none; padding: 0.35rem 0.5rem; border-radius: 6px; display: block; transition: all 0.2s; }
.toc-link:hover { background: rgba(0,71,171,0.06); color: #0047AB; }

/* Content */
.legal-content { background: white; border-radius: 14px; padding: clamp(1.5rem, 4vw, 3rem); border: 1px solid #dde3ee; }
.intro-callout { display: flex; gap: 0.75rem; background: rgba(0,71,171,0.05); border: 1px solid rgba(0,71,171,0.12); border-left: 4px solid #0047AB; border-radius: 8px; padding: 1rem 1.25rem; margin-bottom: 2rem; color: #1e40af; align-items: flex-start; }
.intro-callout p { margin: 0; font-size: 0.93rem; line-height: 1.65; }
.intro-callout svg { flex-shrink: 0; margin-top: 2px; }

.legal-content section { margin-bottom: 2.5rem; padding-bottom: 2.5rem; border-bottom: 1px solid #f0f4f8; }
.legal-content section:last-child { border-bottom: none; margin-bottom: 0; padding-bottom: 0; }
.legal-content h2 { font-size: 1.35rem; font-weight: 800; color: #001a5e; margin-bottom: 1rem; padding-bottom: 0.5rem; border-bottom: 2px solid #f0f4f8; }
.legal-content h3 { font-size: 1rem; font-weight: 700; color: #1f2937; margin: 1.25rem 0 0.5rem; }
.legal-content p { font-size: 0.95rem; color: #374151; line-height: 1.75; margin-bottom: 1rem; }
.legal-content p:last-child { margin-bottom: 0; }
.legal-content ul { list-style: none; padding: 0; margin: 0.75rem 0 1rem; display: flex; flex-direction: column; gap: 0.5rem; }
.legal-content ul li { display: flex; gap: 0.5rem; font-size: 0.93rem; color: #374151; line-height: 1.65; }
.legal-content ul li::before { content: '→'; color: #0047AB; flex-shrink: 0; font-weight: 700; }
.legal-content a { color: #0047AB; text-decoration: none; font-weight: 500; }
.legal-content a:hover { text-decoration: underline; }
.contact-block { background: #f8fafc; border: 1px solid #dde3ee; border-radius: 10px; padding: 1.25rem; margin-top: 1rem; font-size: 0.93rem; line-height: 2; color: #374151; }
</style>